import streamlit as st

# Set page title and icon
st.set_page_config(page_title="About", page_icon=":material/info:")

# About Page
st.title("About the Roget's Word Classifier")

st.write(
    """
    ### MLOps Pipeline Overview
    The core of the classification process is driven by the following pipeline:

    1. **Gemma 1.1 2B**: 
        - A pre-trained model used to generate high-quality word embeddings for words in Roget's Thesaurus.
        - Gemma 1.1 2B is known for its high dimensionality and precision in handling semantic word representation.

    2. **UMAP (Uniform Manifold Approximation and Projection)**:
        - UMAP is used for dimensionality reduction, optimizing the embeddings generated by Gemma to a lower, more manageable dimension.
        - This step is crucial in improving model performance and reducing computation time for predictions.

    3. **Machine Learning Model**:
        - The final classification is performed by a machine learning model (LightGBM) trained on the reduced embeddings.
        - The model predicts the class and section of a given word based on the processed embeddings.

    The pipeline is designed to ensure that every step, from embedding generation to classification, is efficient, scalable, and reliable.
    """
)

st.write(
    """
    ### Key Features
    This project incorporates several modern technologies to ensure seamless operation and performance:
    
    - **MLflow**: For tracking experiments, managing models, and ensuring reproducibility in the training pipeline.
    - **FastAPI**: A high-performance framework used to serve the model and handle API requests for real-time predictions.
    - **Streamlit**: Provides a simple, user-friendly interface for interacting with the model and viewing results.
    - **Docker**: Containerization of the app to ensure easy deployment and scalability across different environments.
    - **Gemma 1.1 2B**: A powerful pre-trained model for embedding word vectors.
    - **UMAP**: Used for dimensionality reduction, optimizing the embeddings before classification.
    """
)

st.write(
    """
    Want to learn more? Check out the [GitHub repository](https://github.com/konstantinosmpouros/Roget_Thesaurus_MLOps) for the code and training pipeline.
    """
)